name: Build Test - Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: dvsa/.github/.github/workflows/nodejs-build.yaml@v4.1.1
    with:
      node-version: '22.x'
      build-command: npm run build
